name: Close stale issues

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  stale:
    if: github.event.label.name != 'bypass-activity'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-issue-message: "This issue has been closed due to lack of activity, if this issue still persists, please re-open it."
          close-issue-label: "closed-no-issue-activity"
          stale-issue-label: "no-issue-activity"
          days-before-stale: 15
          days-before-close: 90